export const products = [
  {
    id: "expel-r",
    name: "EXPel-R",
    price: 549,
    image: "/product-images/cotton/Expel-R.jpeg",
    category: "Bio Insecticide",
    dosage: "250ml per acre",
    whyRecommended: "Highly effective biological caterpillar controller targeting Lepidopteran larvae (Stem Borer, Leaf Folder, Bollworms).",
    borderGlow: "border-red-500/25 hover:border-red-500/50 shadow-red-500/5",
    bgBadge: "bg-red-500/10 border-red-500/20 text-red-400",
    description: "Biological controller that terminates chewing pests and bollworms inside the stems and bolls.",
    technical: "Botanical Herbal Extract",
    doseAcre: "250ml per acre",
    suitableCrop: "Paddy, Cotton, Vegetables",
    targetPest: "Stem Borer, Leaf Folder, Bollworms, Caterpillars",
    applicationMethod: "Foliar Spray",
    advantages: "Biological and 100% organic. Resistance-proof knockdown. Zero chemical residue."
  },
  {
    id: "dodger",
    name: "PIXEL DODGER",
    price: 749,
    image: "/product-images/paddy/Dodger.jpeg",
    category: "Insecticide",
    dosage: "133g per acre",
    whyRecommended: "Systemic action stops sap-feeders immediately, protecting paddy crops from devastating Brown Plant Hopper (BPH).",
    borderGlow: "border-blue-500/25 hover:border-blue-500/50 shadow-blue-500/5",
    bgBadge: "bg-blue-500/10 border-blue-500/20 text-blue-400",
    description: "Formulation: Dinotefuran 15% + Pymetrozine 45% WG. High efficacy systemic protection against sucking pests.",
    technical: "Dinotefuran 15% + Pymetrozine 45% WG",
    doseAcre: "133g per acre",
    suitableCrop: "Paddy",
    targetPest: "Brown Plant Hopper (BPH)",
    applicationMethod: "Foliar Spray (Stem Base)",
    advantages: "Stops feeding in minutes. Prevents Hopper Burn. Long residual control."
  },
  {
    id: "pixel-sensa",
    name: "PIXEL SENSA",
    price: 949,
    image: "/product-images/paddy/Pixel_Sena.jpeg",
    category: "Fungicide",
    dosage: "400ml per acre",
    whyRecommended: "Dual systemic protection that locks out Neck Blast, Leaf Blast, and Sheath Blight in paddy.",
    borderGlow: "border-emerald-500/25 hover:border-emerald-500/50 shadow-emerald-500/5",
    bgBadge: "bg-emerald-500/10 border-emerald-500/20 text-emerald-400",
    description: "Formulation: Picoxystrobin 6.78% + Tricyclazole 20.33% w/w SC. Prevents economic fungal damage and improves grain shine.",
    technical: "Picoxystrobin 6.78% + Tricyclazole 20.33% w/w SC",
    doseAcre: "400ml per acre",
    suitableCrop: "Paddy",
    targetPest: "Rice Blast, Sheath Blight",
    applicationMethod: "Foliar Spray (Booting Stage)",
    advantages: "Dual systemic protection. Prevents neck blast. Improves grain color and shine."
  },
  {
    id: "pixel-4d",
    name: "PIXEL 4D",
    price: 899,
    image: "/product-images/cotton/Pixel4D.jpeg",
    category: "Insecticide",
    dosage: "250g per acre",
    whyRecommended: "Broad-spectrum control targeting Thrips, Whiteflies, and Mites simultaneously on Cotton.",
    borderGlow: "border-orange-500/25 hover:border-orange-500/50 shadow-orange-500/5",
    bgBadge: "bg-orange-500/10 border-orange-500/20 text-orange-400",
    description: "Formulation: Fipronil 10% + Diafenthiuron 30% WG. Vapour action reaches hidden pests under curled leaves.",
    technical: "Fipronil 10% + Diafenthiuron 30% WG",
    doseAcre: "250g per acre",
    suitableCrop: "Cotton",
    targetPest: "Whitefly, Thrips, Mites",
    applicationMethod: "Foliar Spray",
    advantages: "Knocks down sucking insects immediately. Vapour action penetrates curled leaves. 3-in-1 control."
  },
  {
    id: "extend",
    name: "EXTEND",
    price: 549,
    image: "/product-images/cotton/Extend.jpeg",
    category: "Bio Plant Protector",
    dosage: "250ml per acre",
    whyRecommended: "Herbal extracts disrupt sucking pest lifecycles without chemical stress on the plant.",
    borderGlow: "border-green-500/25 hover:border-green-500/50 shadow-green-500/5",
    bgBadge: "bg-green-500/10 border-green-500/20 text-green-400",
    description: "Natural herbal biostimulant that deters Thrips and Mites, leaving zero chemical residue.",
    technical: "Natural Herbal Extract",
    doseAcre: "250ml per acre",
    suitableCrop: "Cotton, Vegetables",
    targetPest: "Thrips, Mites",
    applicationMethod: "Foliar Spray",
    advantages: "Herbal extract base. Safe for organic farming. Zero chemical residues."
  },
  {
    id: "maxcott",
    name: "MAXCOTT",
    price: 799,
    image: "/product-images/cotton/Maxcott.jpeg",
    category: "Insecticide + Growth",
    dosage: "250ml per acre",
    whyRecommended: "Dual-action knocks down Whitefly, Aphid, and Jassid while stimulating lateral branching.",
    borderGlow: "border-indigo-500/25 hover:border-indigo-500/50 shadow-indigo-500/5",
    bgBadge: "bg-indigo-500/10 border-indigo-500/20 text-indigo-400",
    description: "Knocks down sucking insects instantly while stimulating crop vegetative recovery and leaf greening.",
    technical: "Sucking Pest Insecticide + Biostimulant",
    doseAcre: "250ml per acre",
    suitableCrop: "Cotton",
    targetPest: "Whitefly, Aphids, Jassids",
    applicationMethod: "Foliar Spray",
    advantages: "Instant knockdown of sucking insects. Stimulates new shoots. Accelerates vegetative growth."
  },
  {
    id: "flora",
    name: "FLORA",
    price: 499,
    image: "/product-images/vegetables/Flora.jpeg",
    category: "Yield Booster",
    dosage: "250ml per acre",
    whyRecommended: "Reduces blossom drop and directs essential plant nutrients to developing flower bolls or fruits.",
    borderGlow: "border-purple-500/25 hover:border-purple-500/50 shadow-purple-500/5",
    bgBadge: "bg-purple-500/10 border-purple-500/20 text-purple-400",
    description: "Hormonal and nutrient formulation that regulates blossom retention, preventing square and bud drop.",
    technical: "Flowering & Fruit Set Booster",
    doseAcre: "250ml per acre",
    suitableCrop: "Cotton, Vegetables",
    targetPest: "Flower and Bud Drop",
    applicationMethod: "Foliar Spray",
    advantages: "Prevents bud and flower drop. Enhances fruit set percentage. Regulates plant hormone balance."
  },
  {
    id: "builder",
    name: "BUILDER",
    price: 599,
    image: "/product-images/vegetables/Pixel_Builder.jpeg",
    category: "Micronutrient",
    dosage: "250ml per acre",
    whyRecommended: "Supplies crucial Mg, Zn, P, and B to strengthen crop vascular structures before flowering.",
    borderGlow: "border-teal-500/25 hover:border-teal-500/50 shadow-teal-500/5",
    bgBadge: "bg-teal-500/10 border-teal-500/20 text-teal-400",
    description: "Balanced multi-micronutrient formulation featuring Magnesium, Zinc, Phosphorus, and Boron.",
    technical: "Mg + Zn + P + B Complex",
    doseAcre: "250ml per acre",
    suitableCrop: "Vegetables",
    targetPest: "Blossom End Rot, Deformed Fruit",
    applicationMethod: "Foliar Spray or Soil Drip",
    advantages: "Prevents blossom end rot. Supplies crucial trace minerals. Toughens cell walls before flowering."
  },
  {
    id: "probion",
    name: "PROBION",
    price: 449,
    image: "/product-images/vegetables/Probin.jpeg",
    category: "Biostimulant",
    dosage: "250ml per acre",
    whyRecommended: "Delivers pre-digested L-amino acids to help crops recover from drought, heat or chemical stress.",
    borderGlow: "border-cyan-500/25 hover:border-cyan-500/50 shadow-cyan-500/5",
    bgBadge: "bg-cyan-500/10 border-cyan-500/20 text-cyan-400",
    description: "Concentrated organic peptide biostimulant that accelerates vegetative growth and leaf expansion.",
    technical: "L-Amino Acids & Organic Peptides",
    doseAcre: "250ml per acre",
    suitableCrop: "Paddy, Cotton, Vegetables",
    targetPest: "Stunted Growth, Stress",
    applicationMethod: "Foliar Spray",
    advantages: "Bio-available L-amino acids. Accelerates growth. Saves plant metabolic energy under stress."
  },
  {
    id: "k-mate",
    name: "K-MATE",
    price: 399,
    image: "/product-images/vegetables/Pixel_K-Mate.jpeg",
    category: "Soil Health",
    dosage: "250ml per acre",
    whyRecommended: "Concentrated Potassium Humate designed to boost root mass development and unlock locked-up soil phosphorus.",
    borderGlow: "border-yellow-500/25 hover:border-yellow-500/50 shadow-yellow-500/5",
    bgBadge: "bg-yellow-500/10 border-yellow-500/20 text-yellow-400",
    description: "Highly soluble root booster applied via drip fertigation to condition soil structure.",
    technical: "Concentrated Potassium Humate",
    doseAcre: "250ml per acre (or 1-2 kg via drip)",
    suitableCrop: "Vegetables",
    targetPest: "Stunted Roots, Poor Nutrient Intake",
    applicationMethod: "Drip Fertigation / Soil Spray",
    advantages: "Boosts secondary root branching. Restores soil aeration. Unlocks phosphorus binding."
  },
  {
    id: "lamigo",
    name: "LAMIGO",
    price: 849,
    image: "/product-images/vegetables/Lamigo.jpeg",
    category: "Insecticide",
    dosage: "100ml per acre",
    whyRecommended: "Fast-acting contact and systemic control of chewing caterpillars and stem borers.",
    borderGlow: "border-pink-500/25 hover:border-pink-500/50 shadow-pink-500/5",
    bgBadge: "bg-pink-500/10 border-pink-500/20 text-pink-400",
    description: "Formulation: Chlorantraniliprole 9.3% + Lambda-cyhalothrin 4.6% ZC. Fast rainfast knockdown shield.",
    technical: "Chlorantraniliprole 9.3% + Lambda-cyhalothrin 4.6% ZC",
    doseAcre: "100ml per acre",
    suitableCrop: "Paddy, Vegetables",
    targetPest: "Fruit Borer, Caterpillars",
    applicationMethod: "Foliar Spray",
    advantages: "Rainfast in 2 hours. Provides 10-14 days protection. Rapid knockdown on chewing pests."
  },
  {
    id: "aimer",
    name: "AIMER",
    price: 999,
    image: "/product-images/cotton/Expel-R.jpeg", // Fallback image
    category: "Insecticide",
    dosage: "60ml per acre",
    whyRecommended: "Long-duration systemic preventive shield targeting stem borer and leaf folder larvae before entry.",
    borderGlow: "border-rose-500/25 hover:border-rose-500/50 shadow-rose-500/5",
    bgBadge: "bg-rose-500/10 border-rose-500/20 text-rose-400",
    description: "Formulation: Chlorantraniliprole 18.5% SC. Protects vascular channels during active vegetative growth.",
    technical: "Chlorantraniliprole 18.5% SC",
    doseAcre: "60ml per acre",
    suitableCrop: "Paddy, Cotton",
    targetPest: "Stem Borer, Leaf Folder",
    applicationMethod: "Foliar Spray",
    advantages: "Systemic long-term preventive protection. Keeps vascular pathways clear. Safe for target crops."
  },
  {
    id: "pure-auxin",
    name: "PURE AUXIN",
    price: 499,
    image: "/product-images/paddy/Auxin.jpeg",
    category: "PGR",
    dosage: "250ml per acre",
    whyRecommended: "Triggers prolific root network branching and maximizes primary tillering during early Paddy establishment.",
    borderGlow: "border-yellow-500/25 hover:border-yellow-500/50 shadow-yellow-500/5",
    bgBadge: "bg-yellow-500/10 border-yellow-500/20 text-yellow-400",
    description: "Formulated root booster that establishes a strong root foundation at transplanting.",
    technical: "Root Booster Formulation",
    doseAcre: "250ml per acre",
    suitableCrop: "Paddy",
    targetPest: "Weak Roots, Poor Tillering",
    applicationMethod: "Soil Application / Drip",
    advantages: "Triggers lateral root network. Enhances initial tillering count. Quick transplant recovery."
  },
  {
    id: "karbac",
    name: "KARBAC",
    price: 399,
    image: "/product-images/paddy/Pixel_Karbac.jpeg",
    category: "Soil Health",
    dosage: "250ml per acre",
    whyRecommended: "Leonardite Humic + Fulvic Acid complex that conditions soil structure, restoring health season after season.",
    borderGlow: "border-amber-500/25 hover:border-amber-500/50 shadow-amber-500/5",
    bgBadge: "bg-amber-500/10 border-amber-500/20 text-amber-400",
    description: "Contains Humic acid, Fulvic acid, and Leonardite. Restores soil health and increases fertilizer efficiency.",
    technical: "Leonardite Humic + Fulvic Acid",
    doseAcre: "250ml per acre",
    suitableCrop: "Paddy",
    targetPest: "Hard Soil, Low Organic Carbon",
    applicationMethod: "Soil Application",
    advantages: "Restores soil structure and aeration. Improves water holding capacity. Increases microbial count."
  }
];

export function getRecommendedProducts(ids = []) {
  const targetIds = Array.isArray(ids) ? ids.map(id => id.toLowerCase().replace(/[^a-z0-9-]/g, "")) : [];
  
  return products.filter(p => {
    const normId = p.id.toLowerCase().replace(/[^a-z0-9-]/g, "");
    return targetIds.includes(normId);
  });
}